### ISSUE TITLE
Parameter updates are delayed by one message

### ISSUE THREAD

**Issue by Joshuarox100** [KaleidonKep99/CVROSC#1]
When testing with boolean toggles in AAS, the message it sends out contains the value of what it just was, rather than what it just became. In other words, if the toggle is off (0), and I turn it on (1), the OSC message uses the off value (0). This idea is true for integers and floats as well, which may not be preferable for a lot of users.

This can be fixed by putting the assignment statements before the one that sends the messages on lines 63, 74, and 85 in the CVROSC.cs file.

**Comment by KaleidonKep99** [comment]
Oops! I'll fix it asap

**Comment by KaleidonKep99** [comment]
Fixed in 1.1! Thank you for the report, I completely missed this while testing!
Now I understand why I got 0.98 instead of 1 when maxing out the sliders...
