### ISSUE TITLE
Support parameters with / in their name

### ISSUE THREAD

**Issue by kafeijao** [KaleidonKep99/CVROSC#11]
Awesome mod, great work!

It seems I'm having some issues setting parameters that have the character `/` in their name. This might sound weird, but unity does a sub-category thingy when you use `/` for the parameter names.

**Comment by KaleidonKep99** [comment]
Oh, is there any avatar I could test this with?
I didn't know it could support slashes in the parameter names!

**Comment by kafeijao** [comment]
Unfortunately I removed the `/`s to fix the issue for now :(
I think I can try to publish something tomorrow to test (never published an avatar in cvr so no clue what it entails)

**Comment by KaleidonKep99** [comment]
Version 1.6 should be able to interact with these parameters out of the box! Let me know if it works.

**Comment by kafeijao** [comment]
Can confirm is working, thanks!
