### ISSUE TITLE
Framerate completely dies while calibrating full body tracking

### ISSUE THREAD

**Issue by InsaneGrox** [KaleidonKep99/CVROSC#2]
Console just gets spammed with 
[00:44:54.657] [CVROSC] Avatar change detected, loading animation manager... (OT10.41333, NT10.41333)
over and over again while calibrating, the framerate also goes down to less than 1 FPS until both triggers are pulled.

**Comment by KaleidonKep99** [comment]
Ok so apparently the animator gets removed to force the avatar in T-Pose, which makes CVROSC throw a tantrum.

I didn't take into account that they'd do it this way, I'll fix it asap!

**Comment by KaleidonKep99** [comment]
Fixed in v1.2!
