### ISSUE TITLE
Text missing in Readme

### ISSUE THREAD

**Issue by Mar0xy** [KaleidonKep99/CVROSC#3]
As per clause in CVR's ToS it's required to state that you are no way related
"§7.5 When releasing mods to the public, it is required to state, that the mod authors and modification are in no affiliation with ABI and not supported by ABI."

also normally the LICENSE file would be just called LICENSE and not LICENSE.txt

**Comment by KaleidonKep99** [comment]
Oops! Done, thank you for spotting it.
