### ISSUE TITLE
/avatar/change never returns the same ID for an avatar.

### ISSUE THREAD

**Issue by Joshuarox100** [KaleidonKep99/CVROSC#4]
When reloading the same avatar several times, different identifiers are sent every time, making it impossible to distinguish which avatar may be loaded. Without looking too deep into it myself, it seems to likely be caused due to using the hash of the avatar Game Object which can have different instance ID's even when loading the same avatar. The solution for this would be to use or hash something persistent between loads such as the avatar's Asset Info GUID, or the actual name of the avatar itself.

**Comment by Joshuarox100** [comment]
Did some looking around and tinkered with it a bit and found that replacing all instances of PlayerSetup.Instance._avatar.GetHashCode() with MetaPort.Instance.currentAvatarGuid in CVROSC.cs solves the issue. You will also need to import ABI_RC.Core.Savior to access MetaPort.

**Comment by KaleidonKep99** [comment]
Oh yeah I left that as a placeholder while looking around the API... Thank you!
Will be added to 1.4!

**Comment by KaleidonKep99** [comment]
Fixed in 1.4, I'll fix the other things later since I need to do some in-depth research for them.
