### ISSUE TITLE
Updating values externally via OSC results in an unintended feedback message.

### ISSUE THREAD

**Issue by Joshuarox100** [KaleidonKep99/CVROSC#5]
When updating a value through OSC, the cached parameter values are not correctly updated, causing the client to detect a changed variable and output an OSC message with the address and value that was just set.

This is caused by an assignment to a local copy of the parameter when it is being set in the SetParameter function rather than the version cached in the original list. This is resolved by replacing the foreach loop with the equivalent for loop and array accesses within the SetParameter function in CVROSC.cs. The fixed version can be seen in the picture below.

<img width="917" alt="image" src="https://user-images.githubusercontent.com/12418573/181844118-7d592c42-f0e4-4470-816e-99c7ebe38050.png">

**Comment by KaleidonKep99** [comment]
Thank you! I'll fix it once I get around the UI thingy not updating.

**Comment by Joshuarox100** [comment]
Fixed as of version 1.5
